### ISSUE TITLE
Update BootMine link

### ISSUE THREAD

**Issue by io12** [jesings/Bootsweeper#2]
Cool project! And thanks for shouting out my boot sector minesweeper game. I migrated BootMine from GitLab to GitHub so the new link is https://github.com/io12/bootmine (the old link 404s). If you could update the link in the README that would be great. Thanks!

**Comment by jesings** [comment]
I updated the link.
I enjoyed looking at your version again, it's always fun to see the different ways in which a problem can be approached!
